---
##
 # The BSL Reverse Proxy configuration file.
 # _____________________________________________________________________________
 #
 # Created by brightSPARK Labs
 # www.brightsparklabs.com
 ##

reverse_proxy:
  # Settings pertaining to the services.
  services:
    proxy:
      # Whether to use the Acme Staging CA for certificates.
      enable_staging_ca: false

      # Whether to use internal Caddy certificates rather than Acme ones (useful for testing).
      enable_internal_tls: true

  # Settings pertaining to the forwarded networks and routes.
  routing:
    # List of known docker networks to route to. Does not need to include the network for this project.
    # - name: internal-docker-network  <- Internal docker network.
    #   aliases:
    #   - "actual-domain.example.com"  <- Aliases. Same as `docker network create --alias $`
    networks: []

    # List of services to route to.
    # - dns_record: kibana.myproject.local        <- External record.
    #   endpoint: kibana-montitoring-network:5601 <- Internal service.
    routes: []

  # Settings pertaining to debugging the platform.
  debug:
    proxy:
      # Logging levels are DEBUG, INFO, WARN, ERROR, FATAL, PANIC.
      log_level: INFO

metadata:
  # The version of the schema this file conforms to.
  schema_version: 1
