---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: requirements-txt-fixer
- repo: https://github.com/hadolint/hadolint
  rev: v2.12.0
  hooks:
  - id: hadolint-docker
- repo: local
  hooks:
  - id: ruff-lint
    name: Ruff Linter
    description: https://github.com/charliermarsh/ruff
    entry: .venv/bin/ruff
    language: python
    files: \.py$
    args: [check, --fix]
  - id: ruff-formatter
    name: Ruff Formatter
    description: https://github.com/charliermarsh/ruff
    entry: .venv/bin/ruff
    language: python
    files: \.py$
    args: [format]